### ISSUE TITLE
Setting parallax false breaks the site

### ISSUE THREAD

**Issue by xaviemirmon** [tinacms/tina-starter-grande#15]
Hi there 👋

When I set the "Parallax" option in the theme settings to `false` I got a really nasty looking error.

<img width="1022" alt="Screenshot 2019-11-21 at 10 48 26" src="https://user-images.githubusercontent.com/5609840/69333167-1657ef00-0c50-11ea-8910-de49d03c5e50.png">

Pull this down just this morning on Mac OS Catalina

**Comment by spbyrne** [comment]
Strange! Thanks for catching this, I'll take a look.

**Comment by spbyrne** [comment]
I was able to recreate this error, but not from the parallax setting, which was working for me. If I erase the 'overlap' setting I get a compile error, and reverting my change fixes the build issue, but displays the issue you've posted above.

To get things working again I had to run `gatsby clean` before running `gatsby develop`.

I'm not sure why exactly that is, I'll keep looking in to this.

**Comment by spbyrne** [comment]
@xaviemirmon I've implemented a fix that prevents this error coming up for me. Marking this as closed.

Thanks for your bug report! 👍If this comes up again I'll reopen the issue.
