### ISSUE TITLE
Add option to upload image in blogpost body

### ISSUE THREAD

**Issue by nicolad** [tinacms/tina-starter-grande#24]
Not sure if this is related to Tina Grande or `tinacms`, but it would be nice to have the possibility to upload image from the frontend, without the need to do that from markdown file.

**Comment by DirtyF** [comment]
You can now upload images in tinaCMS:

- https://tinacms.org/docs/media
- https://tinacms.org/docs/fields/image
- https://tinacms.org/docs/inline-editing/inline-image

Tina Grande don't demo that feature for now.

**Comment by anindha** [comment]
Adding this feature to the demo would be great!

**Comment by DirtyF** [comment]
@anindha Please just vote for the feature by adding a 👍reaction to the original comment. Thanks.
