### ISSUE TITLE
ESLint warnings

### ISSUE THREAD

**Issue by chokeul8r** [tinacms/tina-starter-grande#38]
Looks like a promising project but I'm not very smart and I cannot make it work. Broken out of the box. 

warn ESLintError:
C:\Users\sue-s\Desktop\tina-starter-grande\src\components\authors.js
  1:8  warning  'React' is defined but never used  no-unused-vars

✖ 1 problem (0 errors, 1 warning)

warn ESLintError:
C:\Users\sue-s\Desktop\tina-starter-grande\src\templates\list.js
  19:10  warning  'authors' is assigned a value but never used  no-unused-vars
  21:17  warning  'limit' is assigned a value but never used    no-unused-vars
  21:24  warning  'skip' is assigned a value but never used     no-unused-vars

✖ 3 problems (0 errors, 3 warnings)

warn ESLintError:
C:\Users\sue-s\Desktop\tina-starter-grande\src\templates\page.js
  20:50  warning  Expected to return a value at the end of arrow function  array-callback-return

✖ 1 problem (0 errors, 1 warning)

⠙ Building development bundle

warn ESLintError:
C:\Users\sue-s\Desktop\tina-starter-grande\src\templates\post.js
  115:6  warning  React Hook useMemo has a missing dependency: 'authors'. Either include it or remove the dependency array    
react-hooks/exhaustive-deps

✖ 1 problem (0 errors, 1 warning)
  0 errors and 1 warning potentially fixable with the `--fix` option.
success Building development bundle - 9.126s

**Comment by Chizzah** [comment]
I'm getting the same issue and I'm also not smart enough. In fact, I couldn't even add tinacms to my site manually lol was hoping this will be the solution

**Comment by spbyrne** [comment]
I see these warnings when running `gatsby develop` but none of them are blocking errors and the site still runs. I'll definitely try to address all the warnings, though.

**Comment by spbyrne** [comment]
I've reduced the number of warnings. The only remaining warnings aren't issues.
