### ISSUE TITLE
Tina Sidebar not scrollable on Safari

### ISSUE THREAD

**Issue by retani** [tinacms/tina-starter-grande#44]
The Sidebar is not scrollable on Safari. Note the lack of the scroll bar. That means that the editor cannot reach all elements. 

I have a large site with many elements, and it's impossible to edit on Safari. Should be a CSS problem. I assume it's a general TinaCMS problem. 

Screenshot made with fresh install of tina-starter-grande as of today. Left: Safari, Right: Chrome. Firefox is fine, too.
<img width="928" alt="TinaScrollProbA" src="https://user-images.githubusercontent.com/3465427/79840017-99bf6d00-83b5-11ea-8180-ae6ea61ebf3e.png">

**Comment by retani** [comment]
ugly quick fix:
````
      <Helmet>
        <style>
          {`div[class^=FormHeader] + div {
            overflow: auto;
          }`}
        </style>
      </Helmet>
````

**Comment by spbyrne** [comment]
I have a fix for this within Tina, PR here: https://github.com/tinacms/tinacms/pull/1042

This should be available in a release next Monday, at which point I'll upgrade Grande & close this issue if appropriate.

**Comment by spbyrne** [comment]
This is fixed! 👍
