### ISSUE TITLE
TypeError: s.useGitForm is not a function

### ISSUE THREAD

**Issue by gib** [tinacms/tina-starter-grande#51]
From a fresh start, following the README setup steps.

![screencapture-localhost-8000-2020-05-29-01_30_11](https://user-images.githubusercontent.com/94830/83279546-8365b780-a192-11ea-830d-67966fb6bc00.png)

**Comment by kendallstrautman** [comment]
Also reported [here](https://github.com/tinacms/gatsby-starter-tinacms/issues/10). Looking into version stuff with `gatsby-tinacms-json`

**Comment by kendallstrautman** [comment]
I can't reproduce this issue, please provide a test repo or more information about your environment!

**Comment by gib** [comment]
I'm on a new mac. After installing node and gatsby-cli globally, I followed the README with the exception of `npm install` rather than yarn. So my repo is a fresh clone of `https://github.com/tinacms/tina-starter-grande.git`

```
$gatsby -v
Gatsby CLI version: 2.12.37
Gatsby version: 2.22.11

$ node -v
v12.17.0
```

I really want to give TinaCMS a try. Thanks for taking a look at it.

**Comment by DiNitride** [comment]
I'm also having this issue. Followed the quickstart guide, though also using npm, so my repo is also a fresh clone of this one.

```
OS: Arch 5.6.15
gatsby-cli: 2.8.15
npm: 6.14.5
node: 14.3.0
```

Console output: https://hastebin.com/uxubofecov.sql

**Comment by cowglow** [comment]
I just opened an old project, upgraded the dependencies, and I'm getting the same issue. Aside from updating the `useLocalJsonForm` method, which is now deprecated, I haven't made any changes. 

```
Gatsby CLI version: 2.10.0
Gatsby version: 2.23.1
Node v12.3.1
```

**Comment by kendallstrautman** [comment]
Try updating _all_ tina packages to their latest versions and this error should go away.
